### ISSUE TITLE
Are swarmalators available to play with?

### ISSUE THREAD

**Issue by youssefavx** [alexbielen/allegro#21]
"In general, Allegro is interested in complexity science and in particular the musical potential of "swarmalators"."

How interesting! I wonder if you've come up with an algorithm to do this. I would love to play if so!

**Comment by alexbielen** [comment]
Hi @youssefavx. Thanks for your interest in the library! I haven't been doing much work on this recently but I'll likely get back into it soon. I'll let you know when I have something that's worth checking out.

**Comment by youssefavx** [comment]
Thank you so much! I love when developers get creative.
